User portal updates
telicent-oss/telicent-ds pull request #88
Opened 2024-08-06 10:06 UTC by AlecsMissangu

Made changes to components and theme to accommodate the user portal application. This PR introduces light UITheme, which is a more stripped back version of our application themes.

Refers to [ticket](https://telicent.atlassian.net/browse/TELFE-400)

2024-08-06 11:36 UTC, ACoolmanTelicent commented
Look great, could we get some tests and screen shots pls

2024-08-07 13:51 UTC, ACoolmanTelicent requested changes
Just rejecting to remove this from my "reviews-requested" list until the screenshots/coverage is done

2024-08-12 15:52 UTC, ACoolmanTelicent approved these changes

2024-08-13 10:22 UTC, dptelicent approved these changes

2024-08-13 10:22 UTC, dptelicent commented on src/v1/theme/style-overrides/component-overrides/button-overrides.ts
> +              uiTheme === "light" || "dark"
Bit confused about what this is doing - should it be
```suggestion
              uiTheme === "light" || uiTheme === "dark"
```
?

2024-08-13 10:32 UTC, dptelicent approved these changes

2024-08-13 10:50 UTC, merged